Mobile tab title
cgkineo/adapt-tabs pull request #4
Opened 2015-10-25 01:35 UTC by chucklorenz

Truncating tab titles on mobile devices isn't always effective. See images.

2 changes proposed:
- Added a mobileTabTitle to allow the author to explicitly assign the desired text. 
- Also centered the item graphic on mobile.
(In the images you'll notice we retained the top tab layout in mobile. This is not germane to the PR, but I did want anyone to get distracted by thinking it was.) 

![screen shot 2015-10-24 at 4 48 24 pm](https://cloud.githubusercontent.com/assets/9489014/10713523/bc455e96-7a89-11e5-9ad2-3ee199b6d11e.png)  

![screen shot 2](https://cloud.githubusercontent.com/assets/9489014/10713618/b690bd88-7a8e-11e5-837c-377f76942423.jpg)
![screen shot 3](https://cloud.githubusercontent.com/assets/9489014/10713620/bbcba704-7a8e-11e5-9944-664019b6e6e0.jpg)

2016-01-22 20:17 UTC, moloko commented
@chucklorenz so sorry I've only just seen this. I think this is a great idea - unfortunately you now have some conflicts, could you resolve these and then I will give this a test?

2016-01-22 20:31 UTC, moloko commented on js/adapt-tabs.js
> +			if (Adapt.device.screenSize == 'small') {
Can I suggest the following to replace this `if` statement? Not only is it DRYer but it allows for the standard tab title to be used as a fallback on mobile if the mobileTitle hasn't been specified.
```
var items = this.model.get('_items');
_.each(items, function (item, index) {
	var tabTitle = (Adapt.device.screenSize === 'small' && item.mobileTabTitle) ? item.mobileTabTitle : item.tabTitle;
	this.$('.tabs-navigation-item-inner').eq(index).html(tabTitle);
});
```

2016-01-22 20:38 UTC, chucklorenz commented on js/adapt-tabs.js
> +			if (Adapt.device.screenSize == 'small') {
Absolutely. I’ll update the PR. I Appreciate the help.

> On Jan 22, 2016, at 2:31 PM, Matt Leathes <notifications@github.com> wrote:
> 
> In js/adapt-tabs.js <https://github.com/cgkineo/adapt-tabs/pull/4#discussion_r50587113>:
> 
> > @@ -51,6 +52,21 @@ define(function(require) {
> >  			});
> >  		},
> >  
> > +		setTabText: function() {
> > +			var items = this.model.get('_items');
> > +			if (Adapt.device.screenSize == 'small') {
> Can I suggest the following to replace this if statement? Not only is it DRYer but it allows for the standard tab title to be used as a fallback on mobile if the mobileTitle hasn't been specified.
> 
> var items = this.model.get('_items');
> _.each(items, function (item, index) {
>     var tabTitle = (Adapt.device.screenSize === 'small' && item.mobileTabTitle) ? item.mobileTabTitle : item.tabTitle;
>     this.$('.tabs-navigation-item-inner').eq(index).html(tabTitle);
> });
> —
> Reply to this email directly or view it on GitHub <https://github.com/cgkineo/adapt-tabs/pull/4/files#r50587113>.
>

2016-11-21 16:31 UTC, tomgreenfield requested changes
Looks like this PR is reverting the changes from @moloko's [commit](https://github.com/cgkineo/adapt-tabs/commit/0aa60c64f9a95c384f64f6d90f328123bf4da0b1). Would you mind updating?

2021-05-24 08:31 UTC, closed without merging